// src/lib/components/Footer.svelte
<script>
	import { onMount } from 'svelte';
	import { getContributors } from '$lib/utils/contributors';
	let contributors = $state([]);

	onMount(async () => {
		contributors = await getContributors();
	});
</script>

<div class="p-16 bg-rich-black text-cool-gray border-t border-space-cadet-light flex flex-col gap-16">
	<div class="flex flex-col md:flex-row gap-8 justify-between">
		<div class="flex flex-col gap-4">
			<img src="yarc-logo.png" class="w-32" alt="YARG Logo" />
				<p class="text-xl">Made with lots of ❤️ by {contributors.length} contributors</p>
		</div>

		<div class="flex flex-col text-xl">
			<h2 class="text-3xl font-bold text-white">GAME</h2>
			<a href="/download">Download</a>
			<a href="https://docs.yarg.in">Documentation</a>
			<a href="/legal">Legal</a>
		</div>

		<div class="flex flex-col text-xl">
			<h2 class="text-3xl font-bold text-white">COMMUNITY</h2>
			<a href="https://discord.gg/yarg">Discord Server</a>
			<a href="https://yarg.myspreadshop.com/">Official Merch</a>
		</div>

		<div class="flex flex-col text-xl">
			<h2 class="text-3xl font-bold text-white">DEVELOPMENT</h2>
			<a href="https://yarg.youtrack.cloud/agiles/147-7/current">Roadmap</a>
			<a href="/content">Content</a>
		</div>
	</div>

	<div class="m-auto flex gap-4 items-center">
		<a href="https://github.com/YARC-Official/YARG"><img src="/svgs/github.svg" class="h-8 text-white" alt="GitHub Logo" /></a>
		<a href="https://discord.gg/yarg"><img src="/svgs/discord.svg" class="h-8 text-white" alt="Discord Logo" /></a>
		<a href="https://youtube.com/@yarggame"><img src="/svgs/youtube.svg" class="h-8 text-white" alt="YouTube Logo" /></a>
		<a href="https://x.com/YARGGame"><img src="/svgs/twitter.svg" class="h-8 text-white" alt="Twitter Logo" /></a>
		<a href="https://bsky.app/yarg.in"><img src="/svgs/bluesky.svg" class="h-8 text-white" alt="Bluesky Logo" /></a>
		<a href="https://instagram.com/yarg.game"><img src="/svgs/instagram.svg" class="h-8 text-white" alt="Instagram Logo" /></a>
		<a href="https://twitch.tv/yarggame"><img src="/svgs/twitch.svg" class="h-8 text-white" alt="Twitch Logo" /></a>
		<a href="https://tiktok.com/@yarggame"><img src="/svgs/tiktok.svg" class="h-8 text-white" alt="TikTok Logo" /></a>
		<a href="https://reddit.com/r/yarg"><img src="/svgs/reddit.svg" class="h-8 text-white" alt="Reddit Logo" /></a>
	</div>
</div>

// src/components/Footer/index.tsx
import React from 'react';
import styles from "./footer.module.css";
import { Discord, Github, Instagram, Reddit, TikTok, Twitch, X, Youtube } from '@/assets/Icons';
import YARGLogo from "@/assets/YARGLogo.svg";
import { getContributors } from '@/utils/contributors';

const Footer: React.FC = async () => {
    const contributors = await getContributors();

  return <footer className={styles.footer}>

    <div className={styles.information}>
        <div className={styles.about}>
            <YARGLogo className={styles.logo}/>

            <div className={styles.description}>
                Yet Another Rhythm Game inspired by beloved classics, delivering an immersive fret rhythm experience.
            </div>
            <div className={styles.contributors}>
                Made with a lot of love by { contributors.length } contributors
            </div>
        </div>

        <div className={styles.navigation}>
            <div className={styles.column}>
                <div className={styles.title}>Game</div>
                <ul>
                    {/* <li>Features</li> */}
                    <a href="https://github.com/YARC-Official/YARC-Launcher/releases/latest">
                        <li>Download</li>
                    </a>
                    {/* <li>Setlist</li> */}
                </ul>
            </div>

            <div className={styles.column}>
                <div className={styles.title}>Community</div>
                <ul>
                    {/* <li>News</li> */}
                    <a href="https://docs.yarg.in/">
                        <li>Documentation</li>
                    </a>
                </ul>
            </div>

            <div className={styles.column}>
                <div className={styles.title}>Development</div>
                <ul>
                    <a href="https://github.com/YARC-Official/YARG-BleedingEdge">
                        <li>Nightly Builds</li>
                    </a>

                    {/* <li>Contributors</li> */}

                    <a href="https://yarg.youtrack.cloud/issues">
                        <li>Roadmap</li>
                    </a>
                </ul>
            </div>
        </div>
    </div>

    <div className={styles.copyright}>
        <div className={styles.company}>
            <div className={styles.link}>YARC</div>
            <div className={styles.link}>Terms</div>
            <div className={styles.link}>Privacy</div>
            <div className={styles.link}>Cookies</div>
        </div>

        <div className={styles.socials}>
            <a href="https://discord.gg/yarg" target="_blank">
                <Discord />
            </a>
            <a href="https://github.com/YARC-Official" target="_blank">
                <Github />
            </a>
            <a href="https://x.com/yarggame" target="_blank">
                <X />
            </a>
            <a href="https://www.youtube.com/@YARGGame" target="_blank">
                <Youtube />
            </a>
            <a href="https://www.reddit.com/r/yarg/" target="_blank">
                <Reddit />
            </a>
            <a href="https://www.twitch.tv/yarggame" target="_blank">
                <Twitch />
            </a>
            <a href="https://www.instagram.com/yarg.game" target="_blank">
                <Instagram />
            </a>
            <a href="https://www.tiktok.com/@yarggame" target="_blank">
                <TikTok />
            </a>
        </div>
    </div>

  </footer>;
}

export default Footer;
